Flexible:
Workcenter:         Wkc000
  Setup:              A;B;2 A;C;3 A;D;4 B;A;4 B;C;5 B;D;6 C;A;3 C;B;6 C;D;7 D;A;2 D;B;5 D;C;8
  Machine:            Wkc000.000
    Release:            0
    Status:             B
  Machine:            Wkc000.001
    Release:            0
    Status:             B

Workcenter:         Wkc001
  Setup:
  Machine:            Wkc001.000
    Release:            0
    Status:             A

Workcenter:         Wkc002
  Setup:              A;A;1 A;B;2 A;C;3 A;D;4 B;A;5 B;B;6 B;C;7 B;D;8 C;A;9 C;B;10 C;C;11 C;D;12 D;A;13 D;B;14 D;C;15 D;D;16
  Machine:            Wkc002.000
    Release:            0
    Status:             C
  Machine:            Wkc002.001
    Release:            0
    Status:             C

Workcenter:         Wkc003
  Setup:
  Machine:            Wkc003.000
    Release:            0
    Status:             A

